[tool.black]
line-length = 79
force-exclude = '''
/(
    \.venv
)
'''

[tool.isort]
profile = "black"
line_length = 79
skip_gitignore = true
skip_glob = [
    "**/.venv/*",
]

[tool.mypy]
exclude = [
    ".venv",
]
ignore_missing_imports = true